language: C

sudo:
  - required

os:
  - linux

dist:
  - trusty

compiler:
  - gcc

before_install:
  # apt-get install
  - sudo apt-get install -y gcc-4.7-arm-linux-gnueabi libncurses5-dev binutils-arm-linux-gnueabi 
  - export CROSS_COMPILE=arm-linux-gnueabi-
  - export ARCH=arm
  - sudo ln -s /usr/bin/arm-linux-gnueabi-gcc-4.7 /usr/bin/arm-linux-gnueabi-gcc

  # Download the kernel
  - git clone --depth 1 --branch release https://github.com/CONPROSYS/linux-kernel_3.2.0.CONPROSYS.git $PWD/build
  - export KERNELDIR=$PWD/build

  # export conprosys-sdk
  - export CPS_SDK_ROOTDIR=$PWD
  - export CPS_SDK_TARGET_NAME=CPS-MCS341-DSX.novlan
  - export CPS_SDK_PRODUCT_TYPE=CPS-MCS341-DSX
  - export CPS_SDK_LAN_TYPE=novlan
  - export CPS_SDK_INSTALL_FULL_DIR=$CPS_SDK_ROOT_DIR/target/CPS-MCS341-DSX.novlan

before_script:
  - cd $KERNELDIR
  - ls /usr/bin/arm* 
  - make distclean
  - make defconfig CPS-MCS341-DSX.novlan_defconfig
  - make prepare
  - cd ./scripts
  - make -C $KERNELDIR M=`pwd` modules
  - cd $TRAVIS_BUILD_DIR/
  
script:
  - make
  - make release_copy
  - sudo make modules_install

after_script:
  - sudo $TRAVIS_BUILD_DIR/technical-report
  - cd $TRAVIS_BUILD_DIR/driver/release/
  - ./driver_version_check

